### ISSUE TITLE
The 's' in "testris"

### ISSUE THREAD

**Issue by livibetter** [douglasknowman/testris#1]
I am curious why there is a letter 's' in the name, does it represent something special?

**Comment by douglasvinis** [comment]
No, nothing special, actually is ridiculously simple: testris = test + tetris

**Comment by livibetter** [comment]
Aha! [Someone did guess that](https://www.youtube.com/watch?v=CCxIJyvSAdA&lc=z12qibypgvuhcxemd22ve10rvomlcrznf)!

"test" did come into my mind while I was typing, but I didn't believe it could be that simple, in fact, I somehow believed it was a typo until I read README how it's written along with "Tetris," so I knew it's most likely not a typo. In the end, it's really that simple.

**Comment by douglasvinis** [comment]
haha, by the way, thank you for made a video about the game. =D
